{
 "title": "Data drift monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Graduation year distribution ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CAST(features->>'gradyear' AS INTEGER) AS value,\r\n  COUNT(*) AS count\r\nFROM\r\n  past_predictions\r\nWHERE\r\n  insertion_timestamp >= NOW() - interval '2 minutes'\r\n  AND features->>'gradyear' IS NOT NULL\r\n  AND CAST(features->>'gradyear' AS INTEGER) BETWEEN 1900 AND 2025\r\nGROUP BY\r\n  value\r\nORDER BY\r\n  value;\r\n"
    }
   ]
  },
  {
   "title": "Number of friends distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CAST(features->>'NumberOffriends' AS INTEGER) AS value,\r\n  COUNT(*) AS count\r\nFROM\r\n  past_predictions\r\nWHERE\r\n  insertion_timestamp >= NOW() - interval '2 minutes'\r\n  AND features->>'NumberOffriends' IS NOT NULL\r\n  AND CAST(features->>'NumberOffriends' AS INTEGER) BETWEEN 0 AND 600\r\nGROUP BY\r\n  value\r\nORDER BY\r\n  value;\r\n"
    }
   ]
  },
  {
   "title": "Age Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CAST(features->>'age' AS INTEGER) AS value,\r\n  COUNT(*) AS count\r\nFROM\r\n  past_predictions\r\nWHERE\r\n  insertion_timestamp >= NOW() - interval '2 minutes'\r\n  AND features->>'age' IS NOT NULL\r\n  AND CAST(features->>'age' AS INTEGER) BETWEEN 0 AND 100\r\nGROUP BY\r\n  value\r\nORDER BY\r\n  value;\r\n"
    }
   ]
  }
 ]
}