{
 "title": "Dashboard for Data Engineer",
 "description": "Nice dashboard for Data engineer of the friends-app",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Batch Quality Segmentation (Last 10 min)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH categorized AS (\r\n  SELECT\r\n    CASE\r\n      WHEN (num_affected_samples::decimal / NULLIF(num_samples, 0)) <= 0.10 THEN 'Quite good'\r\n      WHEN (num_affected_samples::decimal / NULLIF(num_samples, 0)) > 0.10 AND (num_affected_samples::decimal / NULLIF(num_samples, 0)) <= 0.30 THEN 'To be reviewed'\r\n      WHEN (num_affected_samples::decimal / NULLIF(num_samples, 0)) > 0.30 THEN 'Toxic'\r\n      ELSE 'Unknown'\r\n    END AS quality_category\r\n  FROM\r\n    marketing_ingestion_statistics.batch_columns_stats\r\n  WHERE\r\n    insertion_timestamp >= NOW() - interval '10 minutes'\r\n)\r\nSELECT\r\n  quality_category,\r\n  COALESCE(ROUND(COUNT(*) * 100.0 / NULLIF((SELECT COUNT(*) FROM categorized),0),2),0) AS percent_of_total\r\nFROM\r\n  categorized\r\nGROUP BY\r\n  quality_category\r\nORDER BY\r\n  quality_category;\r\n"
    }
   ]
  },
  {
   "title": "Valid and Invalid Sample Rates",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_trunc('minute', insertion_timestamp) AS time,\r\n  ROUND(100.0 * SUM(num_data_errors)::numeric / NULLIF(SUM(num_samples), 0), 2) AS invalid_rate,\r\n  ROUND(100.0 - (100.0 * SUM(num_data_errors)::numeric / NULLIF(SUM(num_samples), 0)), 2) AS valid_rate\r\nFROM marketing_ingestion_statistics.batch_columns_stats\r\nWHERE $__timeFilter(insertion_timestamp)\r\nGROUP BY time\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Individual Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "WITH total_per_minute AS (\r\n  SELECT\r\n    date_trunc('minute', insertion_timestamp) AS time,\r\n    SUM(num_samples) AS total_samples\r\n  FROM marketing_ingestion_statistics.batch_columns_stats\r\n  WHERE $__timeFilter(insertion_timestamp)\r\n  GROUP BY time\r\n),\r\nerror_breakdown AS (\r\n  SELECT\r\n    date_trunc('minute', insertion_timestamp) AS time,\r\n    error_type,\r\n    SUM(num_affected_records) AS error_count\r\n  FROM marketing_ingestion_statistics.feature_error_stats\r\n  WHERE $__timeFilter(insertion_timestamp)\r\n  GROUP BY time, error_type\r\n)\r\nSELECT\r\n  t.time,\r\n  e.error_type,\r\n  ROUND(100.0 * e.error_count::numeric / NULLIF(t.total_samples, 0), 2) AS error_rate\r\nFROM total_per_minute t\r\nJOIN error_breakdown e ON e.time = t.time\r\nORDER BY t.time, e.error_type;\r\n"
    }
   ]
  },
  {
   "title": "Missing and New errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date_trunc('minute', insertion_timestamp)::timestamp AS time,\r\n  COUNT(*) AS missing_errors\r\nFROM marketing_ingestion_statistics.column_error_types\r\nWHERE $__timeFilter(insertion_timestamp)\r\n  AND col_error_type = 'missing'\r\nGROUP BY time\r\nORDER BY time;\r\n"
    },
    {
     "rawSql": "SELECT\r\n  date_trunc('minute', insertion_timestamp)::timestamp AS time,\r\n  COUNT(*) AS new_errors\r\nFROM marketing_ingestion_statistics.column_error_types\r\nWHERE $__timeFilter(insertion_timestamp)\r\n  AND col_error_type = 'new'\r\nGROUP BY time\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "Failed Expectation (By Feature)",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  f.feature,\r\n  f.error_type,\r\n  SUM(f.num_affected_records) AS error_count\r\nFROM marketing_ingestion_statistics.feature_error_stats f\r\nGROUP BY f.feature, f.error_type\r\nORDER BY error_count DESC;\r\n"
    }
   ]
  }
 ]
}