{
 "title": "Data Drift Monitoring",
 "description": "Data Drift Monitoring For Data Scienctist",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Training Age Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  value::int AS value,\r\n  count\r\nFROM\r\n  training_feature_distribution\r\nWHERE\r\n  feature_name = 'age'\r\nORDER BY\r\n  value\r\n"
    }
   ]
  },
  {
   "title": "Inference age distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ROUND(CAST(features->>'age' AS NUMERIC))::INTEGER AS value,\r\n  COUNT(*) AS count\r\nFROM\r\n  past_predictions\r\nWHERE\r\n  insertion_timestamp >=  now() AT TIME ZONE 'UTC' - interval '20 minutes'\r\nAND features->>'age' IS NOT NULL\r\n  AND features->>'age' ~ '^[0-9]+(\\.[0-9]+)?$'  -- filters numeric values\r\n  AND CAST(features->>'age' AS NUMERIC) BETWEEN 0 AND 600\r\nGROUP BY\r\n  value\r\nORDER BY\r\n  value;\r\n"
    }
   ]
  },
  {
   "title": "Training gradyear Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  value::int AS value,\r\n  count\r\nFROM\r\n  training_feature_distribution\r\nWHERE\r\n  feature_name = 'gradyear'\r\nORDER BY\r\n  value\r\n"
    }
   ]
  },
  {
   "title": "Inference gradyear distribution ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ROUND(CAST(features->>'gradyear' AS NUMERIC))::INTEGER AS value,\r\n  COUNT(*) AS count\r\nFROM\r\n  past_predictions\r\nWHERE\r\n  insertion_timestamp >=  now() AT TIME ZONE 'UTC' - interval '20 minutes'\r\nAND features->>'gradyear' IS NOT NULL\r\n  AND features->>'gradyear' ~ '^[0-9]+(\\.[0-9]+)?$'  -- filters numeric values\r\n  AND CAST(features->>'gradyear' AS NUMERIC) BETWEEN 1900 AND 2025\r\nGROUP BY\r\n  value\r\nORDER BY\r\n  value;\r\n"
    }
   ]
  },
  {
   "title": "Training Number Of friends Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  value::int AS value,\r\n  count\r\nFROM\r\n  training_feature_distribution\r\nWHERE\r\n  feature_name = 'NumberOffriends'\r\nORDER BY\r\n  value\r\n"
    }
   ]
  },
  {
   "title": " Inference Number of friends distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ROUND(CAST(features->>'NumberOffriends' AS NUMERIC))::INTEGER AS value,\r\n  COUNT(*) AS count\r\nFROM\r\n  past_predictions\r\nWHERE\r\n  insertion_timestamp >=  now() AT TIME ZONE 'UTC' - interval '20 minutes'\r\nAND features->>'NumberOffriends' IS NOT NULL\r\n  AND features->>'NumberOffriends' ~ '^[0-9]+(\\.[0-9]+)?$'  -- filters numeric values\r\n  AND CAST(features->>'NumberOffriends' AS NUMERIC) BETWEEN 0 AND 600\r\nGROUP BY\r\n  value\r\nORDER BY\r\n  value;\r\n"
    }
   ]
  }
 ]
}